version: "3"
services: 
    core:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /lib/modules:/lib/modules
            - ./dotcore:/root/.core
            - .:/dtn_routing
        tty: true
        privileged: true
        cap_add:
            - NET_ADMIN
        tmpfs:
            - /tmp:exec,mode=777,size=200G
        environment:
            - CORE_PARAMS=/dtn_routing/scenarios/default.imn
            - DISPLAY
            - BACKEND
            - ALGORITHMS
    builder:
        build:
            context: .
            dockerfile: builder.Dockerfile
        volumes:
            - /lib/modules:/lib/modules
            - ./dtn7-go:/dtn7-go
        tty: true
        privileged: true
        cap_add:
            - NET_ADMIN
        tmpfs:
            - /tmp:exec,mode=777,size=200G
        environment:
            - CORE_PARAMS=/dtn_routing/scenarios/default.imn
            - DISPLAY
