version: "3"
services:
    core:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /lib/modules:/lib/modules
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./dotcore:/root/.core
            - .:/dtn_routing
            - /research_data/sommer2020cadr/paper/maci-docker-compose/maci_data/binary_files:/research_data
        tty: true
        privileged: true
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        tmpfs:
            - /tmp:exec,mode=777,size=200G
        environment:
            - CORE_PARAMS=/dtn_routing/scenarios/wanderwege/wanderwege.xml
            - DISPLAY
            - BACKEND
            - ALGORITHMS
