[Scenario]
xml = "/dtn_routing/scenarios/responders/responders.xml"
wifi_range = 275.0

[Experiment]
seed = 0
routing = "epidemic"
payload_size = 1000
bundles_per_node = 5
payload_path = "/tmp/payload"
generate_payload = false

[REST]
address = "localhost"
agent_port = 8080
routing_port = 35043
