[Scenario]
xml = "/dtn_routing/scenarios/responders/responders.xml"
wifi_range = 275.0

[Experiment]
seed = 0
routing = "epidemic"
payload_size = 10000
generate_payload = false
payload_path = "/tmp/payload"
bundles_per_node = 10

[REST]
address = "localhost"
agent_port = 8080
routing_port = 35043
