[Node]
name = "n4"

[REST]
address = "localhost"
routing_port = 35044

[Scenario]
xml = "../../scenarios/minimal/minimal.xml"
movements = "../../scenarios/minimal/minimal.ns_movements"

[Experiment]
routing = "context_complex"