[Node]
name = "n17"
endpoint_id = "dtn://n2/"

[Scenario]
xml = "../../scenarios/responders/responders.xml"

[REST]
address = "localhost"
agent_port = 8080
routing_port = 35043

[Experiment]
seed = 0
routing = "epidemic"
payload_size = 10000
bundles_per_node = 70
generate_payload=true
payload_path=""
